### ISSUE TITLE
Hello author, can you add support for IL2CPP, I use IL2CPP will show abnormal.

### ISSUE THREAD

**Issue by qq357075581** [DenchiSoft/UnityAspectRatioController#5]
Hello author, can you add support for IL2CPP, I use IL2CPP will show abnormal.

**Comment by BallistiX09** [comment]
@qq357075581 Did you manage to get this working? It's giving me a missing DLL error when I try to use it on a UWP Windows IL2CPP build

**Comment by qq357075581** [comment]
> @qq357075581你成功搞定了吗?当我试图在Uwp窗口IL2CPP构建中使用它时,它给了我一个缺失的DLL错误

yes，I solved the problem.In IL2CPP, some code needs to be changed to static,If you want, I can share it with you, you can leave your email.

**Comment by BallistiX09** [comment]
> > @qq357075581你成功搞定了吗?当我试图在Uwp窗口IL2CPP构建中使用它时,它给了我一个缺失的DLL错误
> 
> yes，I solved the problem.In IL2CPP, some code needs to be changed to static,If you want, I can share it with you, you can leave your email.

That would be perfect, thank you! My email address is elegant.bowl9391@fastmail.com

**Comment by qq357075581** [comment]
> > > @qq357075581你成功搞定了吗?当我试图在Uwp窗口IL2CPP构建中使用它时,它给了我一个缺失的DLL错误
> > 
> > 
> > 是的,我解决了这个问题。在IL2CPP中,有些代码需要修改为静态,如果你愿意,我可以和你分享,你可以留下你的电子邮件。
> 
> 太好了,谢谢!我的电邮地址是[ 优雅。鲍尔斯9391@快速邮件网站](mailto:elegant.bowl9391@fastmail.com)
Sent。

**Comment by GEMLittleY** [comment]
> > @qq357075581你成功搞定了吗?当我试图在Uwp窗口IL2CPP构建中使用它时,它给了我一个缺失的DLL错误
> 
> yes，I solved the problem.In IL2CPP, some code needs to be changed to static,If you want, I can share it with you, you can leave your email.

作者大哥，我也需要一份，项目必须要用IL2CPP，拜托，我的邮箱：514208625@qq.com

**Comment by DenchiSoft** [comment]
If there's a fix required to make this work with IL2CPP, please add it as a pull request.

**Comment by GEMLittleY** [comment]
> If there's a fix required to make this work with IL2CPP, please add it as a pull request.
Can someone please push it to us

**Comment by GEMLittleY** [comment]
> If there's a fix required to make this work with IL2CPP, please add it as a pull request.

Log is :


NotSupportedException: IL2CPP does not support marshaling delegates that point to instance methods to native code. The method we're attempting to marshal is: AspectRatioController::<Start>b__39_0
  at AspectRatioController.Start () [0x00000] in <00000000000000000000000000000000>:0

**Comment by bluelettered** [comment]
> > > [@qq357075581](https://github.com/qq357075581)你成功搞定了吗?当我试图在Uwp窗口IL2CPP构建中使用它时,它给了我一个缺失的DLL错误
> > 
> > 
> > yes，I solved the problem.In IL2CPP, some code needs to be changed to static,If you want, I can share it with you, you can leave your email.
> 
> That would be perfect, thank you! My email address is [elegant.bowl9391@fastmail.com](mailto:elegant.bowl9391@fastmail.com)

Excuse me, did you ever receive a fix, and could you upload it? My game is also built with IL2CPP and would greatly benefit from this.
